### ISSUE TITLE
VCU118 REF_CLK_FREQ is changed?

### ISSUE THREAD

**Issue by shuntarot** [ucsdsysnet/corundum#4]
Hi

I've compiled fpga_100g on VCU118 and connected to Mellanox ConnectX4.
It works on old XCI IP generation flow, but latest TCL IP generation flow, they can't link-up.

I think it is because CMAC REF_CLK_FREQ is changed from 156.25 to 161.1328125. As far as I test, below change to cmac_usplus_0/1.tcl fix this issue.

```
-   CONFIG.GT_REF_CLK_FREQ {161.1328125} \
+   CONFIG.GT_REF_CLK_FREQ {156.25} \
```

Thanks

**Comment by alexforencich** [comment]
Apologies, that should be fixed now.  Looks like I got the gtwizard settings correct for 10G, but didn't adjust the CMAC cores.  This is what happens when I don't have continuous access to all of the various hardware targets, I periodically make changes to keep things consistent, but then occasionally introduce bugs by not being able to test the design on every target.
